name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: act10ns/slack@v2
      with:
        status: starting
        channel: '#testing'
        message: Starting Docker Build and Push...
      if: always()

    -  
        name: Checkout
        uses: actions/checkout@v4
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest

    -   name: Notify Slack - End
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          message: ":white_check_mark: Docker Build and Push completed!"
          channel: '#testing'
        if: always()